
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author migue
 */
public class Cajero extends javax.swing.JFrame {
    private float saldo = 1500;
    boolean punto = false;
    

    /**
     * Creates new form Cajero
     */
    public Cajero() {
        initComponents();
        setLocationRelativeTo(null);
        lblSaldo.setText("$"+ Float.toString(saldo));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Retiro = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblSaldo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        txtDepositar = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        btnDepositar = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        txtRetirar = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        btnRetirar = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 200));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);
        jPanel2.add(jPanel5, java.awt.BorderLayout.LINE_END);
        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_END);
        jPanel2.add(jPanel7, java.awt.BorderLayout.LINE_START);

        lblSaldo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblSaldo.setText("$");
        jPanel8.add(lblSaldo);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        Retiro.addTab("Saldo", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel9, java.awt.BorderLayout.PAGE_START);
        jPanel3.add(jPanel10, java.awt.BorderLayout.LINE_END);
        jPanel3.add(jPanel11, java.awt.BorderLayout.PAGE_END);
        jPanel3.add(jPanel12, java.awt.BorderLayout.LINE_START);

        jPanel13.setLayout(new java.awt.GridLayout(3, 2));

        jLabel4.setText("Cantidad a Depositar");
        jPanel13.add(jLabel4);

        jPanel14.setLayout(new java.awt.GridLayout(1, 1));

        txtDepositar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDepositarKeyTyped(evt);
            }
        });
        jPanel14.add(txtDepositar);

        jPanel13.add(jPanel14);
        jPanel13.add(jPanel15);
        jPanel13.add(jPanel16);

        jPanel17.setLayout(new java.awt.GridLayout(1, 1));

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });
        jPanel17.add(btnDepositar);

        jPanel13.add(jPanel17);

        jPanel18.setLayout(new java.awt.GridLayout(1, 1));
        jPanel13.add(jPanel18);

        jPanel3.add(jPanel13, java.awt.BorderLayout.CENTER);

        Retiro.addTab("Deposito ", jPanel3);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel19, java.awt.BorderLayout.PAGE_START);
        jPanel1.add(jPanel20, java.awt.BorderLayout.LINE_END);
        jPanel1.add(jPanel21, java.awt.BorderLayout.PAGE_END);
        jPanel1.add(jPanel22, java.awt.BorderLayout.LINE_START);

        jPanel23.setLayout(new java.awt.GridLayout(3, 2));

        jLabel6.setText("Canridad a Retirar ");
        jPanel23.add(jLabel6);

        jPanel24.setLayout(new java.awt.GridLayout(1, 1));

        txtRetirar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRetirarKeyTyped(evt);
            }
        });
        jPanel24.add(txtRetirar);

        jPanel23.add(jPanel24);
        jPanel23.add(jPanel25);
        jPanel23.add(jPanel26);

        jPanel27.setLayout(new java.awt.GridLayout(1, 1));

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        jPanel27.add(btnRetirar);

        jPanel23.add(jPanel27);

        jPanel28.setLayout(new java.awt.GridLayout(1, 1));
        jPanel23.add(jPanel28);

        jPanel1.add(jPanel23, java.awt.BorderLayout.CENTER);

        Retiro.addTab("Retiro ", jPanel1);

        getContentPane().add(Retiro);

        jMenu2.setText("Archivo");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Cerrar Sesion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtDepositarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepositarKeyTyped
        // TODO add your handling code here:
        
        int letra = evt.getKeyChar();
        
       
       if((letra >=48 && letra <=57) || (letra ==46)) {
          /* if(punto ==false && (letra >=48 && letra <=57)){
               System.out.println(punto);
           }else{
                evt.consume();
           }
           if(letra ==46){
               punto = true;
           }
           */
        }else{
             evt.consume();
        }
    }//GEN-LAST:event_txtDepositarKeyTyped

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        // TODO add your handling code here:
        String depositar = txtDepositar.getText();
        int p = depositar.indexOf(".");
        int p1 = depositar.indexOf(".", p+1 );
        if(p1 != -1){
        depositar = depositar.substring(0,p1);
        }
        System.out.println(depositar);
        saldo = saldo + Float.parseFloat(depositar);
        lblSaldo.setText(Float.toString(saldo));
        JOptionPane.showMessageDialog(null,"Deposito exitoso");
        txtDepositar.setText("");
        
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void txtRetirarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetirarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetirarKeyTyped

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        // TODO add your handling code here:
        
        String Retirar = txtRetirar.getText();
        int p = Retirar.indexOf(".");
        int p1 = Retirar.indexOf(".", p+1 );
        if(p1 != -1){
        Retirar = Retirar.substring(0,p1);
        }
        if (saldo >= Float.parseFloat(Retirar)){
        saldo = saldo - Float.parseFloat(Retirar);
        lblSaldo.setText(Float.toString(saldo));
        JOptionPane.showMessageDialog(null,"Retiro exitoso");
        txtRetirar.setText("");
        }else{
            JOptionPane.showMessageDialog(null,"Saldo insuficiente");
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Retiro;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtDepositar;
    private javax.swing.JTextField txtRetirar;
    // End of variables declaration//GEN-END:variables
}
