/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcial3;

import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class Productos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        comboP = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        comboD = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        optIVA = new javax.swing.JCheckBox();
        optsinIVA = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblProducto = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        btncalcular = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        btncerrar = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(400, 250));
        setMinimumSize(new java.awt.Dimension(400, 250));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 250));

        jPanel1.setPreferredSize(new java.awt.Dimension(20, 158));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jPanel6.setLayout(new java.awt.GridLayout(1, 3));

        jPanel9.setLayout(new java.awt.GridLayout(1, 1));

        comboP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Juegos", "Juguetes", "Productos" }));
        jPanel9.add(comboP);

        jPanel6.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 1));

        comboD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Descuento 10%", "Descuento 20%", "Sin descuento ", " ", " ", " " }));
        comboD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDActionPerformed(evt);
            }
        });
        jPanel10.add(comboD);

        jPanel6.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(2, 1));

        buttonGroup1.add(optIVA);
        optIVA.setText("con IVA");
        jPanel11.add(optIVA);

        buttonGroup1.add(optsinIVA);
        optsinIVA.setSelected(true);
        optsinIVA.setText("Sin IVA");
        optsinIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optsinIVAActionPerformed(evt);
            }
        });
        jPanel11.add(optsinIVA);

        jPanel6.add(jPanel11);

        jPanel2.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jPanel12.setLayout(new java.awt.GridLayout(3, 1));

        jLabel1.setText("Producto");
        jPanel12.add(jLabel1);

        jLabel2.setText("Descuento");
        jPanel12.add(jLabel2);

        jLabel3.setText("Con IVA o sin IVA");
        jPanel12.add(jLabel3);

        jPanel7.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridLayout(3, 1));
        jPanel13.add(lblProducto);
        jPanel13.add(lblDescuento);
        jPanel13.add(lblIVA);

        jPanel7.add(jPanel13);

        jPanel2.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 3));

        jPanel14.setLayout(new java.awt.GridLayout(1, 1));

        btncalcular.setText("Calcular");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });
        jPanel14.add(btncalcular);

        jPanel8.add(jPanel14);

        jPanel15.setLayout(new java.awt.GridLayout(1, 1));

        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        jPanel15.add(btncerrar);

        jPanel8.add(jPanel15);

        jPanel16.setLayout(new java.awt.GridLayout(1, 1));
        jPanel16.add(lblTotal);

        jPanel8.add(jPanel16);

        jPanel2.add(jPanel8);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel3.setPreferredSize(new java.awt.Dimension(20, 238));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optsinIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optsinIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optsinIVAActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        // TODO add your handling code here:
        float juego = 500.00f;
        float juguete  = 100.00f;
        float producto = 50.00f;
        float precio = 0.0f;
        float descuento = 0.0f;
        float preciot = 0.0f;
        float IVA = 0.0f;
        
        String p = (String)comboP.getSelectedItem();
        String d = (String)comboD.getSelectedItem();
        
        if(optIVA.isSelected()){
            if(p.equals("Juegos")){
                IVA = juego *0.16f;
                precio = juego * 1.16f;
            }
            if(p.equals("Juguetes")){
                IVA = juguete * 0.16f;
                precio = juguete *1.16f;
            }
            if(p.equals("Productos")){
                IVA = producto *0.16f;
                precio = producto *1.16f;
            }
            
        }else if(optsinIVA.isSelected()){
            if(p.equals("Juegos")){
                IVA = 0;
                precio = juego;
            }
            if(p.equals("Juguetes")){
                IVA = 0;
                precio = juguete;
            }
            if(p.equals("Productos")){
                IVA = 0;
                precio = producto;
            }
            
            
        }
        if(d.equals("Descuento 10%")){
            descuento = precio * 0.1f;
            preciot = precio- descuento;
            
        }else if(d.equals("Descuento 20%")){
            descuento = precio * 0.2f;
            preciot = precio- descuento;
        }else if(d.equals("Sin descuento")){
          
            preciot = precio;
        }
        
        lblProducto.setText(Float.toString(precio));
        lblDescuento.setText(Float.toString(descuento));
        lblIVA.setText(Float.toString(IVA));
        lblTotal.setText(Float.toString(preciot));
    
        
        
    }//GEN-LAST:event_btncalcularActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void comboDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btncerrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboD;
    private javax.swing.JComboBox<String> comboP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JCheckBox optIVA;
    private javax.swing.JCheckBox optsinIVA;
    // End of variables declaration//GEN-END:variables
}
