
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author migue
 */
public class venPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public venPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txtEscribeundato = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        btnIdentificar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        txtV1 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        txtV2 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        txtvariable1 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        txtvariable2 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        btnaceptar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jPanel6.setLayout(new java.awt.GridLayout(1, 3));

        jPanel9.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escribe un dato");
        jPanel9.add(jLabel1);

        jPanel6.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 1));

        txtEscribeundato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEscribeundato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEscribeundatoActionPerformed(evt);
            }
        });
        jPanel10.add(txtEscribeundato);

        jPanel6.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(1, 1));

        btnIdentificar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIdentificar.setText("Identificar");
        btnIdentificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdentificarActionPerformed(evt);
            }
        });
        jPanel11.add(btnIdentificar);

        jPanel6.add(jPanel11);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 3));

        jPanel12.setLayout(new java.awt.GridLayout(2, 1));

        jPanel15.setLayout(new java.awt.GridLayout(1, 1));

        txtV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtV1ActionPerformed(evt);
            }
        });
        jPanel15.add(txtV1);

        jPanel12.add(jPanel15);

        jPanel16.setLayout(new java.awt.GridLayout(1, 1));

        txtV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtV2ActionPerformed(evt);
            }
        });
        jPanel16.add(txtV2);

        jPanel12.add(jPanel16);

        jPanel7.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridLayout(1, 1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel13.add(jLabel2);

        jPanel7.add(jPanel13);

        jPanel14.setLayout(new java.awt.GridLayout(1, 1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Cambiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton2);

        jPanel7.add(jPanel14);

        jPanel1.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 3));

        jPanel17.setLayout(new java.awt.GridLayout(1, 1));

        txtvariable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel17.add(txtvariable1);

        jPanel8.add(jPanel17);

        jPanel18.setLayout(new java.awt.GridLayout(1, 1));

        txtvariable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel18.add(txtvariable2);

        jPanel8.add(jPanel18);

        jPanel19.setLayout(new java.awt.GridLayout(1, 1));

        btnaceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnaceptar.setText("jButton4");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });
        jPanel19.add(btnaceptar);

        jPanel8.add(jPanel19);

        jPanel1.add(jPanel8);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setPreferredSize(new java.awt.Dimension(20, 200));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(20, 200));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEscribeundatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEscribeundatoActionPerformed
        // TODO add your handling code here:
        
      
      
       
           
           
               
           
       
     
       
       
      
    }//GEN-LAST:event_txtEscribeundatoActionPerformed
     
   
       
    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        // TODO add your handling code here: 
        String n1 = txtvariable1.getText();
        String n2 = txtvariable2.getText();
        float n1r = Float.parseFloat(n1);
       float n2r = Float.parseFloat(n2);
       double resultado = Math.pow(n1r,n2r);
        
        JOptionPane.showMessageDialog(null," EL resultado es:"+ resultado);
        
        
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           String p1 = txtV1.getText();
           String p2 = txtV2.getText();
           
           
             if(p1.length()==0 || p2.length()==0){
                    JOptionPane.showMessageDialog(null,"No se dectecto ningun caracter para comparar");
          }else{
           if(p1.contains(p2)){
               JOptionPane.showMessageDialog(null, "La letra ingresada si se encuentra en la palabra ingresada");
               jLabel2.setText("si coinciden");
           }else{
               JOptionPane.showMessageDialog(null,"La palabra ingresada no se encontro en la palabra");
               jLabel2.setText("No coninciden");

           }
                }   
     
        
       
              
    }//GEN-LAST:event_jButton2ActionPerformed
       public boolean Contains(String a){
        String V1 = txtV1.getText();
        System.out.println(V1.contains(txtV2.getText())); 
        return true;
        }
    private void txtV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtV1ActionPerformed
        // TODO add your handling code here:
     
       
    }//GEN-LAST:event_txtV1ActionPerformed

    private void btnIdentificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdentificarActionPerformed
        // TODO add your handling code here:
       String V = txtEscribeundato.getText();
   
      if(V.length()==0){
           JOptionPane.showMessageDialog(null, "No se detectaaron caracteres");
      }else{
           if(Validarletras(V)){
               JOptionPane.showMessageDialog(null,"Los caracteres ingresados son letras");
           }
           if(Validarnumeros(V)){
               JOptionPane.showMessageDialog(null, "Los caracteres ingresados son numeros");
           }
           if(Validarsimbolos(V)){
               JOptionPane.showMessageDialog(null,"Los caracteres ingresados son simbolos");
           }
      }
      
       
       
    }//GEN-LAST:event_btnIdentificarActionPerformed
 public boolean Validarletras(String a ){
            int c = 0;
            for (int i = 0; i <a.length(); i++) {
               if(a.codePointAt(i)>=65 && a.codePointAt(i)<=90 || a.codePointAt(i)>=97 && a.codePointAt(i)<=122){ 
                    c++;          
                }
                
                }
               if(c==a.length()){
                   return true;
               }else{
                   return false;
               }
                
        }
        
         
        public boolean Validarnumeros(String a ){
            int c = 0;
            for(int i = 0; i<a.length(); i++){
                if(a.codePointAt(i)>=48 && a.codePointAt(i)<=57){
                    c++;
                }
            }
            if(c==a.length()){
            return true;
            }else{
            return false;
            }
            
     
            }
        
        public boolean Validarsimbolos(String a ){
            int c = 0;
            for(int i = 0; i<a.length();i++){
                    if(a.codePointAt(i)==64|| a.codePointAt(i)==36 || a.codePointAt(i)==35){
                        c++;
                    }
            }
            if(c== a.length()){
                return true;
            }else{
                return false;
            }
        }
     
    
    private void txtV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtV2ActionPerformed

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2AncestorAdded
                                            
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIdentificar;
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField txtEscribeundato;
    private javax.swing.JTextField txtV1;
    private javax.swing.JTextField txtV2;
    private javax.swing.JTextField txtvariable1;
    private javax.swing.JTextField txtvariable2;
    // End of variables declaration//GEN-END:variables
}
